#!/bin/bash

echo "apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs-provisioner
  namespace: kube-system
spec:
  chart: nfs-subdir-external-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  targetNamespace: kube-system
  set:
    nfs.server: $nfsServer
    nfs.path: $nfsPath
    storageClass.name: nfs
    storageClass.reclaimPolicy: $reclaimPolicy"
