#!/bin/bash

echo "apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: $provisionerName
  namespace: kube-system
spec:
  chart: nfs-subdir-external-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  targetNamespace: kube-system
  set:
    nfs.server: $nfsServer
    nfs.path: $nfsPath
    storageClass.name: $storageClassName
    storageClass.reclaimPolicy: $reclaimPolicy
    storageClass.provisionerName: $provisionerName
    storageClass.defaultClass: true"
