apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs-provisioner
  namespace: kube-system
spec:
  chart: nfs-subdir-external-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  targetNamespace: kube-system
  set:
    nfs.server: 192.168.32.32
    nfs.path: /mnt/Z2/Kubernetes-state/k3s-public
    storageClass.name: nfs
    storageClass.reclaimPolicy: Retain
